/**
 * Seed tune list, used once to populate a new account.
 * Sourced from `Tunes - Sheet1.csv` (title, type, Next Tempo).
 */
import type { TuneType } from "./types";

export interface SeedTune {
  title: string;
  type: TuneType;
  tempo: number;
  beats: number;
}

export const SEED_TUNES: SeedTune[] = [
  { title: "Green Mountain", type: "Reel", tempo: 100, beats: 4 },
  { title: "Ballydesmond No.3", type: "Hornpipe/Slow Reel/Polka", tempo: 100, beats: 4 },
  { title: "Club Ceili", type: "Jig/Slip Jig", tempo: 80, beats: 2 },
  { title: "Haunted House", type: "Jig/Slip Jig", tempo: 80, beats: 2 },
  { title: "Little Diamond Polka", type: "Hornpipe/Slow Reel/Polka", tempo: 100, beats: 4 },
  { title: "Murroe Polka", type: "Hornpipe/Slow Reel/Polka", tempo: 100, beats: 4 },
  { title: "Maids of Ardath", type: "Hornpipe/Slow Reel/Polka", tempo: 100, beats: 4 },
  { title: "Boyne Hunt", type: "Reel", tempo: 100, beats: 4 },
  { title: "Shannon Breeze", type: "Reel", tempo: 100, beats: 4 },
  { title: "Red Haired Lass", type: "Reel", tempo: 100, beats: 4 },
  { title: "Tobin's Favourite", type: "Jig/Slip Jig", tempo: 80, beats: 2 },
  { title: "Tulla Reel", type: "Reel", tempo: 100, beats: 4 },
  { title: "Skylark", type: "Reel", tempo: 100, beats: 4 },
  { title: "Roaring Mary", type: "Reel", tempo: 100, beats: 4 },
  { title: "Brosna Slide", type: "Jig/Slip Jig", tempo: 80, beats: 2 },
  { title: "O'Keefe's", type: "Jig/Slip Jig", tempo: 80, beats: 2 },
  { title: "Dennis Murphy's", type: "Jig/Slip Jig", tempo: 80, beats: 2 },
  { title: "U-Bar 1B", type: "Jig/Slip Jig", tempo: 130, beats: 2 },
  { title: "U-Bar 1A", type: "Jig/Slip Jig", tempo: 130, beats: 2 },
  { title: "Humours of Glendart", type: "Jig/Slip Jig", tempo: 130, beats: 2 },
  { title: "Concertina Reel", type: "Reel", tempo: 200, beats: 4 },
  { title: "Over the Moor to Maggie", type: "Reel", tempo: 200, beats: 4 },
  { title: "Farewell to Whalley Range", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Sporting Paddy", type: "Reel", tempo: 220, beats: 4 },
  { title: "Donnybrook Fair Jig", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Jig of Slurs", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Rolling in the Ryegrass", type: "Reel", tempo: 220, beats: 4 },
  { title: "Tenpenny Bit", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Old Favourite", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Kilmaley", type: "Reel", tempo: 220, beats: 4 },
  { title: "Geese in the Bog", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Teetotaller", type: "Reel", tempo: 220, beats: 4 },
  { title: "Humours of Ballyloughlin", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Sligo Maid", type: "Reel", tempo: 220, beats: 4 },
  { title: "Tabhair Dom do Lamh", type: "Waltz", tempo: 120, beats: 3 },
  { title: "Garrett Barry's Jig", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Man of the House", type: "Reel", tempo: 220, beats: 4 },
  { title: "Rose in the Heather", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Ships are Sailing", type: "Reel", tempo: 220, beats: 4 },
  { title: "Dunmore Lasses", type: "Reel", tempo: 220, beats: 4 },
  { title: "I Buried My Wife & Danced On Her Grave", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Otter's Holt", type: "Reel", tempo: 220, beats: 4 },
  { title: "Tarbolton Reel", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Rolling Waves", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Ashokan Farewell", type: "Waltz", tempo: 120, beats: 3 },
  { title: "The Atholl Highlanders", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Castle Kelly", type: "Reel", tempo: 220, beats: 4 },
  { title: "Saddle the Pony", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Foxhunters Slip Jig", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Foxhunters Reel", type: "Reel", tempo: 220, beats: 4 },
  { title: "Haste to the Wedding", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Merrily Kiss the Quaker", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Humours of Tulla", type: "Reel", tempo: 220, beats: 4 },
  { title: "Jim Ward's", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Mist Covered Mountain", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Britches Full of Stitches", type: "Hornpipe/Slow Reel/Polka", tempo: 130, beats: 4 },
  { title: "The Irish Washerwoman", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Jenny's Welcome To Charlie", type: "Reel", tempo: 220, beats: 4 },
  { title: "Mason's Apron", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Maid of Mount Kisco", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Earl's Chair", type: "Reel", tempo: 220, beats: 4 },
  { title: "Scatter the Mud", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Bucks of Oranmore", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Piper's of Roguery", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Floating Crowbar", type: "Reel", tempo: 220, beats: 4 },
  { title: "Wall of Liscarroll", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Trim the Velvet", type: "Reel", tempo: 220, beats: 4 },
  { title: "Lord Ramsay's", type: "Reel", tempo: 220, beats: 4 },
  { title: "Frank's Reel", type: "Reel", tempo: 220, beats: 4 },
  { title: "King Of The Pipers", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Clumsy Lover", type: "Reel", tempo: 220, beats: 4 },
  { title: "Jenny Picking Cockles", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Trip To Sligo", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Road To Lisdoonvarna", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "John Ryan's Polka", type: "Hornpipe/Slow Reel/Polka", tempo: 130, beats: 4 },
  { title: "Whiskey Before Breakfast", type: "Reel", tempo: 220, beats: 4 },
  { title: "My Darling Asleep", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Wise Maid", type: "Reel", tempo: 220, beats: 4 },
  { title: "Jenny's Chickens", type: "Reel", tempo: 220, beats: 4 },
  { title: "Toss The Feathers (Em)", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Congress Reel", type: "Reel", tempo: 220, beats: 4 },
  { title: "Toss The Feathers (D)", type: "Reel", tempo: 220, beats: 4 },
  { title: "Jenny's Wedding", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Morning Dew", type: "Reel", tempo: 220, beats: 4 },
  { title: "Miss McLeod's", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Gravel Walks", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Merry Maids Of Mitchelstown", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Merry Blacksmith", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Star Of Munster", type: "Reel", tempo: 220, beats: 4 },
  { title: "Cup Of Tea", type: "Reel", tempo: 220, beats: 4 },
  { title: "Calliope Jig", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Rights of Man", type: "Hornpipe/Slow Reel/Polka", tempo: 130, beats: 4 },
  { title: "The Grumbling Old Man And Woman", type: "Reel", tempo: 220, beats: 4 },
  { title: "Scotch Mary", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Mountain Road", type: "Reel", tempo: 220, beats: 4 },
  { title: "Tripping Up The Stairs", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Hag's Purse", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Boys of Bluehill", type: "Hornpipe/Slow Reel/Polka", tempo: 130, beats: 4 },
  { title: "St Anne's Reel", type: "Reel", tempo: 220, beats: 4 },
  { title: "Samhradh", type: "Hornpipe/Slow Reel/Polka", tempo: 130, beats: 4 },
  { title: "The Collier's Jig", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Lark in the Morning", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Inisheer", type: "Waltz", tempo: 120, beats: 3 },
  { title: "Off To California", type: "Hornpipe/Slow Reel/Polka", tempo: 130, beats: 4 },
  { title: "Bunker Hill", type: "Reel", tempo: 220, beats: 4 },
  { title: "From Night Till Morn", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Old Torn Petticoat", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Monoghan", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Stool Of Repentance", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Tatter Jack Walsh's", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Hardiman The Fiddler", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Wind That Shakes The Barley", type: "Reel", tempo: 220, beats: 4 },
  { title: "Bean An Ti At Lar", type: "Reel", tempo: 220, beats: 4 },
  { title: "Musical Priest", type: "Reel", tempo: 220, beats: 4 },
  { title: "Sally Gardens", type: "Reel", tempo: 220, beats: 4 },
  { title: "Pigeon On The Gate", type: "Reel", tempo: 220, beats: 4 },
  { title: "Farewell To Erin", type: "Reel", tempo: 220, beats: 4 },
  { title: "King Of The Fairies", type: "Hornpipe/Slow Reel/Polka", tempo: 130, beats: 4 },
  { title: "McGoldrick's Jig", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Sportsman's Hornpipe", type: "Hornpipe/Slow Reel/Polka", tempo: 130, beats: 4 },
  { title: "Sí Bheag Sí Mhór", type: "Waltz", tempo: 120, beats: 3 },
  { title: "Cliffs Of Moher", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Kiss For A Fig", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Scartaglen Slide", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Blackthorn Stick", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Out On The Ocean", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Drummond Castle", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Hag At The Churn", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Rolling Wave", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Rambling Pitchfork", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Connachtman's Rambles", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Blarney Pilgrim", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Swallowtail Jig", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Banish Misfortune", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Trip To Athlone", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Beekeeper", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Lilting Banshee", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Donegal", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Kesh Jig", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Morrison's Jig", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Kevin McHugh's", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Diplodocus", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Apples In Winter", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Fig for a Kiss", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "The Butterfly", type: "Jig/Slip Jig", tempo: 140, beats: 2 },
  { title: "Rakish Paddy", type: "Reel", tempo: 220, beats: 4 },
  { title: "Drowsy Maggie", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Banshee", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Silver Spear", type: "Reel", tempo: 220, beats: 4 },
  { title: "Sean Sa Cheo", type: "Reel", tempo: 220, beats: 4 },
  { title: "Cooley's Reel", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Maid Behind The Bar", type: "Reel", tempo: 220, beats: 4 },
  { title: "Spootiskerry", type: "Reel", tempo: 220, beats: 4 },
  { title: "Willafjord", type: "Reel", tempo: 220, beats: 4 },
  { title: "Ragged Hank Of Yarn", type: "Reel", tempo: 220, beats: 4 },
  { title: "The Ivy Leaf", type: "Reel", tempo: 220, beats: 4 },
  { title: "Dinny O'Brien's", type: "Reel", tempo: 220, beats: 4 },
  { title: "Farewell To Connacht", type: "Reel", tempo: 220, beats: 4 },
];
